In [1]:
import torch
import torch.nn.functional as F
import matplotlib.pyplot as plt
%matplotlib inline

In [2]:
words = open('names.txt', 'r').read().splitlines()
words[:5]

['emma', 'olivia', 'ava', 'isabella', 'sophia']

In [3]:
chars = sorted(list(set(''.join(words))))
stoi = {s:i+1 for i, s in enumerate(chars)}
stoi['.'] = 0
itos = {i:s for s, i in stoi.items()}
itos

{1: 'a',
 2: 'b',
 3: 'c',
 4: 'd',
 5: 'e',
 6: 'f',
 7: 'g',
 8: 'h',
 9: 'i',
 10: 'j',
 11: 'k',
 12: 'l',
 13: 'm',
 14: 'n',
 15: 'o',
 16: 'p',
 17: 'q',
 18: 'r',
 19: 's',
 20: 't',
 21: 'u',
 22: 'v',
 23: 'w',
 24: 'x',
 25: 'y',
 26: 'z',
 0: '.'}

In [4]:
block_size = 3
X, Y = [], []

for w in words[:5]:
    print(w)
    context = [0]*block_size
    for ch in w +'.':
        ix = stoi[ch]
        X.append(context)
        Y.append(ix)
        print(''.join(itos[i] for i in context), '--->', itos[ix])
        context = context[1:] + [ix]
X = torch.tensor(X)
Y = torch.tensor(Y)

emma
... ---> e
..e ---> m
.em ---> m
emm ---> a
mma ---> .
olivia
... ---> o
..o ---> l
.ol ---> i
oli ---> v
liv ---> i
ivi ---> a
via ---> .
ava
... ---> a
..a ---> v
.av ---> a
ava ---> .
isabella
... ---> i
..i ---> s
.is ---> a
isa ---> b
sab ---> e
abe ---> l
bel ---> l
ell ---> a
lla ---> .
sophia
... ---> s
..s ---> o
.so ---> p
sop ---> h
oph ---> i
phi ---> a
hia ---> .


In [5]:
C = torch.randn((27, 2))

In [6]:
emb = C[X]

In [12]:
W1 = torch.randn(6, 100)
b1 = torch.randn(100)

In [13]:
 emb[:, 0, :]  

tensor([[ 0.8850, -0.5780],
        [ 0.8850, -0.5780],
        [ 0.8850, -0.5780],
        [ 0.8788,  0.5746],
        [-0.2390, -0.3881],
        [ 0.8850, -0.5780],
        [ 0.8850, -0.5780],
        [ 0.8850, -0.5780],
        [ 1.0638,  0.6828],
        [ 0.5621, -2.2577],
        [-0.6900, -0.6699],
        [-0.1402,  0.8824],
        [ 0.8850, -0.5780],
        [ 0.8850, -0.5780],
        [ 0.8850, -0.5780],
        [-1.6553,  0.8988],
        [ 0.8850, -0.5780],
        [ 0.8850, -0.5780],
        [ 0.8850, -0.5780],
        [-0.6900, -0.6699],
        [-1.4073, -0.4447],
        [-1.6553,  0.8988],
        [ 0.1233,  0.4318],
        [ 0.8788,  0.5746],
        [ 0.5621, -2.2577],
        [ 0.8850, -0.5780],
        [ 0.8850, -0.5780],
        [ 0.8850, -0.5780],
        [-1.4073, -0.4447],
        [ 1.0638,  0.6828],
        [ 0.4166, -1.4690],
        [-0.8465,  0.8111]])

In [8]:
#torch.cat([emb[:,0, :], emb[:,0, :], emb[:,0, :]], 1).shape

torch.Size([32, 6])

In [9]:
#torch.cat(torch.unbind(emb, 1), 1).shape

torch.Size([32, 6])

In [10]:
emb.view(32, 6)

tensor([[ 0.8850, -0.5780,  0.8850, -0.5780,  0.8850, -0.5780],
        [ 0.8850, -0.5780,  0.8850, -0.5780,  0.8788,  0.5746],
        [ 0.8850, -0.5780,  0.8788,  0.5746, -0.2390, -0.3881],
        [ 0.8788,  0.5746, -0.2390, -0.3881, -0.2390, -0.3881],
        [-0.2390, -0.3881, -0.2390, -0.3881, -1.6553,  0.8988],
        [ 0.8850, -0.5780,  0.8850, -0.5780,  0.8850, -0.5780],
        [ 0.8850, -0.5780,  0.8850, -0.5780,  1.0638,  0.6828],
        [ 0.8850, -0.5780,  1.0638,  0.6828,  0.5621, -2.2577],
        [ 1.0638,  0.6828,  0.5621, -2.2577, -0.6900, -0.6699],
        [ 0.5621, -2.2577, -0.6900, -0.6699, -0.1402,  0.8824],
        [-0.6900, -0.6699, -0.1402,  0.8824, -0.6900, -0.6699],
        [-0.1402,  0.8824, -0.6900, -0.6699, -1.6553,  0.8988],
        [ 0.8850, -0.5780,  0.8850, -0.5780,  0.8850, -0.5780],
        [ 0.8850, -0.5780,  0.8850, -0.5780, -1.6553,  0.8988],
        [ 0.8850, -0.5780, -1.6553,  0.8988, -0.1402,  0.8824],
        [-1.6553,  0.8988, -0.1402,  0.8

In [16]:
h = torch.tanh(emb.view(-1, 6)@W1 + b1)

In [17]:
h.shape

torch.Size([32, 100])

In [18]:
W2 =torch.randn((100, 27))
b2 = torch.randn(27)

In [19]:
logits = h @ W2 + b2

In [20]:
logits.shape

torch.Size([32, 27])

In [21]:
counts = logits.exp()

In [22]:
probs = counts/counts.sum(1, keepdim=True)

In [23]:
probs.shape

torch.Size([32, 27])

In [24]:
probs[0].sum()

tensor(1.0000)

In [28]:
loss = -probs[torch.arange(32), Y].log().mean()
loss

tensor(14.9705)

In [25]:
torch.arange(32)

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31])