In [1]:
import torch

In [2]:
a = torch.tensor([1, 2, 3])
print(a.dtype)
print(a.shape)
print(a[0], a[1], a[2])
a[0] = 5
print(a)

b = torch.tensor([[1 ,2, 3], [4, 5, 6]])
print(b.shape)

torch.int64
torch.Size([3])
tensor(1) tensor(2) tensor(3)
tensor([5, 2, 3])
torch.Size([2, 3])


In [3]:
a0 = torch.zeros([2, 2])
print(a0)
a1 = torch.zeros((2,2))
print(a1)
a2 = torch.zeros(2,2)
print(a2)

b = torch.ones([1, 2])
print(b)

c = torch.full([2, 2], 7)
print(c)

d = torch.eye(2)
print(d)

e = torch.randn([2, 2])
print(e)

tensor([[0., 0.],
        [0., 0.]])
tensor([[0., 0.],
        [0., 0.]])
tensor([[0., 0.],
        [0., 0.]])
tensor([[1., 1.]])
tensor([[7, 7],
        [7, 7]])
tensor([[1., 0.],
        [0., 1.]])
tensor([[ 0.6069,  0.4499],
        [-0.1615, -0.6437]])


In [4]:
a = torch.tensor([[1, 2, 3], [4, 5, 6], [6, 7, 8]])
print(a)

b = a[:2, 1:3]
print(b)

print(a[0, 1])
b[0, 0] = 77
print(a[0, 1])

tensor([[1, 2, 3],
        [4, 5, 6],
        [6, 7, 8]])
tensor([[2, 3],
        [5, 6]])
tensor(2)
tensor(77)


In [5]:
a = torch.tensor([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
row_r1 = a[1, :]
row_r2 = a[1:2, :]
print(row_r1, row_r1.shape)
print(row_r2, row_r2.shape)

col_r1 = a[:, 1]
col_r2 = a[:, 1:2]
print(col_r1, col_r1.shape)
print(col_r2, col_r2.shape)

tensor([5, 6, 7, 8]) torch.Size([4])
tensor([[5, 6, 7, 8]]) torch.Size([1, 4])
tensor([ 2,  6, 10]) torch.Size([3])
tensor([[ 2],
        [ 6],
        [10]]) torch.Size([3, 1])


In [6]:
a = torch.tensor([[1, 2], [3, 4], [5, 6]])
print(a[[0 , 1, 2], [0, 1, 0]])
print(torch.tensor([a[0, 0], a[1, 1], a[2,0]]))

print(a[[0, 0], [1, 1]])
print(torch.tensor([a[0, 1], a[0,1]]))

tensor([1, 4, 5])
tensor([1, 4, 5])
tensor([2, 2])
tensor([2, 2])


In [7]:
a = torch.tensor([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]])
print(a)

b = torch.tensor([0, 2, 0, 1])
print(a[torch.arange(4), b])

a[torch.arange(4), b] += 10
print(a)

tensor([[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9],
        [10, 11, 12]])
tensor([ 1,  6,  7, 11])
tensor([[11,  2,  3],
        [ 4,  5, 16],
        [17,  8,  9],
        [10, 21, 12]])


In [8]:
a = torch.tensor([[1,2], [3, 4], [5, 6]])
bool_idx = (a>2)
print(bool_idx)
print(a[bool_idx])
print(a[a>2])

tensor([[False, False],
        [ True,  True],
        [ True,  True]])
tensor([3, 4, 5, 6])
tensor([3, 4, 5, 6])


In [9]:
x = torch.tensor([1, 2])
print(x.dtype)

x = torch.tensor([1.0, 2.0])
print(x.dtype)

x = torch.tensor([1, 2], dtype=torch.int64)
print(x.dtype)

torch.int64
torch.float32
torch.int64


In [10]:
x = torch.tensor([[1, 2], [3, 4]], dtype=torch.float64)
y = torch.tensor([[5, 6], [7, 8]], dtype=torch.float64)

print(x+y)
print(torch.add(x, y))

print(x-y)
print(torch.subtract(x,y))

print(x*y)
print(torch.multiply(x, y))

print(x/y)
print(torch.divide(x, y))

print(torch.sqrt(x))


tensor([[ 6.,  8.],
        [10., 12.]], dtype=torch.float64)
tensor([[ 6.,  8.],
        [10., 12.]], dtype=torch.float64)
tensor([[-4., -4.],
        [-4., -4.]], dtype=torch.float64)
tensor([[-4., -4.],
        [-4., -4.]], dtype=torch.float64)
tensor([[ 5., 12.],
        [21., 32.]], dtype=torch.float64)
tensor([[ 5., 12.],
        [21., 32.]], dtype=torch.float64)
tensor([[0.2000, 0.3333],
        [0.4286, 0.5000]], dtype=torch.float64)
tensor([[0.2000, 0.3333],
        [0.4286, 0.5000]], dtype=torch.float64)
tensor([[1.0000, 1.4142],
        [1.7321, 2.0000]], dtype=torch.float64)


In [11]:
x = torch.tensor([[1, 2], [3, 4]])
y = torch.tensor([[5, 6], [7, 8]])
v = torch.tensor([9, 10])
w = torch.tensor([11, 12])

print(v.dot(w))
print(torch.dot(v, w))

torch.linalg.multi_dot([x, v])
torch.linalg.multi_dot([x, y])

tensor(219)
tensor(219)


tensor([[19, 22],
        [43, 50]])

In [12]:
x = torch.tensor([[1, 2], [3, 4]])

print(torch.sum(x))
print(torch.sum(x, axis=0))
print(torch.sum(x, axis=1))

tensor(10)
tensor([4, 6])
tensor([3, 7])


In [13]:
x = torch.tensor([[1, 2], [3, 4]])
print(x)
print(torch.transpose(x, 0, 1))



tensor([[1, 2],
        [3, 4]])
tensor([[1, 3],
        [2, 4]])


In [15]:
x = torch.tensor([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]])
v = torch.tensor([[1, 0, 1]])
y = torch.empty_like(x)

for i in range(4):
    y[i, :] = x[i, :] + v
print(y)

tensor([[ 2,  2,  4],
        [ 5,  5,  7],
        [ 8,  8, 10],
        [11, 11, 13]])


In [17]:
x = torch.tensor([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]])
v = torch.tensor([1, 0, 1])
vv = torch.tile(v, [4,1])
print(vv)

y = x + vv
print(y)

tensor([[1, 0, 1],
        [1, 0, 1],
        [1, 0, 1],
        [1, 0, 1]])
tensor([[ 2,  2,  4],
        [ 5,  5,  7],
        [ 8,  8, 10],
        [11, 11, 13]])


In [18]:
x = torch.tensor([[1, 2, 3] ,[4, 5, 6], [7, 8, 9], [10, 11, 12]])
v = torch.tensor([1, 0, 1])
y = x + v
print(y)

tensor([[ 2,  2,  4],
        [ 5,  5,  7],
        [ 8,  8, 10],
        [11, 11, 13]])


In [23]:
v = torch.tensor([1, 2, 3])
w = torch.tensor([4, 5])
print(torch.reshape(v, [3, 1]) * w)

x = torch.tensor([[1, 2, 3], [4, 5, 6]])
print(x + v)

print(torch.transpose(torch.transpose(x, 0, 1) + w, 0, 1))

print(x + torch.reshape(w, [2, 1]))
print(x*2)

tensor([[ 4,  5],
        [ 8, 10],
        [12, 15]])
tensor([[2, 4, 6],
        [5, 7, 9]])
tensor([[ 5,  6,  7],
        [ 9, 10, 11]])
tensor([[ 5,  6,  7],
        [ 9, 10, 11]])
tensor([[ 2,  4,  6],
        [ 8, 10, 12]])
